### ISSUE TITLE
Docs for handling errors? 

### ISSUE THREAD

**Issue by dey-dey** [doxout/simple-router#2]
currently if no routes are found it throws `reportError`. don't see any docs on how to handle this. tried to add middleware before routes and catch `next` but it still throws.

**Comment by spion** [comment]
Adding an error-handling middleware (with 4 arguments) after the last route should do it:

```js
app.use(function (err, req, res, next) {
    if (err.code && res.answer)
        res.answer(err);
    else next(err);
});
```
